name: make-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  create-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build NetBlame addin
        run: |
          dotnet build  src\NetBlame\NetBlameAddIn.sln --configuration Release -p:Version=${{ inputs.version }}
        shell: cmd

      - name: Create artifacts directory
        run: mkdir bin\MSO-Scripts

      - name: Create archive with all scripts
        shell: pwsh
        run: |
          Get-ChildItem -Path "src" -File | Copy-Item -Destination "bin\MSO-Scripts"
          Copy-Item -Path "src\BETA" -Destination "bin\MSO-Scripts\BETA" -Recurse
          Copy-Item -Path "src\NetBlame\bin\Release\net8.0\*" -Destination "bin\MSO-Scripts\BETA\ADDIN" -Recurse
          Copy-Item -Path "src\OETW" -Destination "bin\MSO-Scripts\OETW" -Recurse
          Copy-Item -Path "src\PreWin10" -Destination "bin\MSO-Scripts\PreWin10" -Recurse
          Copy-Item -Path "src\WPAP" -Destination "bin\MSO-Scripts\WPAP" -Recurse
          Copy-Item -Path "src\WPRP" -Destination "bin\MSO-Scripts\WPRP" -Recurse
          Compress-Archive -Path "bin\MSO-Scripts" -DestinationPath "bin\MSO-Scripts-${{ inputs.version }}.zip"

      - name: Publish release
        run: gh release create v${{ inputs.version }} --title "Release v${{ inputs.version }}" "bin\MSO-Scripts-${{ inputs.version }}.zip" --notes "Manual release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
